Repository puppetlabs/puppet-strings, pull requests merged in 2022-10, with the labels that each got.

#316 (MAINT) Add release workflows
  .github/workflows/release.yml
  .github/workflows/release_prep.yml
  .gitignore
Labels: maintenance

#320 (MAINT) Fix snyk workflow
  .github/workflows/snyk.yml
Labels: maintenance

#322 (MAINT) Refresh readme
  README.md
Labels: maintenance

#323 (MAINT) Update CI workflow
  .github/workflows/ci.yml
Labels: maintenance

#321 (MAINT) Add community labeller
  .github/workflows/labeller.yml
Labels: maintenance

#317 Use tilde heredocs for readability
  .rubocop.yml
  spec/acceptance/generate_markdown_spec.rb
  spec/fixtures/acceptance/modules/test/lib/puppet/datatypes/acceptancedatatype.rb
  spec/fixtures/ruby/data_type.rb
  spec/fixtures/ruby/func3x.rb
  spec/fixtures/ruby/resource_api.rb
  spec/fixtures/ruby/resource_type.rb
  spec/unit/puppet-strings/describe_spec.rb
  spec/unit/puppet-strings/json_spec.rb
  spec/unit/puppet-strings/markdown/base_spec.rb
  spec/unit/puppet-strings/yard/code_objects/task_spec.rb
  spec/unit/puppet-strings/yard/handlers/json/task_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/puppet/class_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/puppet/data_type_alias_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/puppet/defined_type_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/puppet/function_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/ruby/data_type_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/ruby/function_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/ruby/provider_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/ruby/rsapi_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/ruby/type_extras_handler_spec.rb
  spec/unit/puppet-strings/yard/handlers/ruby/type_handler_spec.rb
  spec/unit/puppet-strings/yard/parsers/json/parser_spec.rb
  spec/unit/puppet-strings/yard/parsers/json/task_statement_spec.rb
  spec/unit/puppet-strings/yard/parsers/puppet/parser_spec.rb
  spec/unit/puppet-strings/yard/util_spec.rb
Labels: feature

#324 (MAINT) Add matrix for acceptance tests
  .github/workflows/ci.yml
  Gemfile
  Rakefile
  puppet-strings.gemspec
Labels: maintenance

#325 (MAINT) Remove version constraint for rake
  Gemfile
Labels: maintenance

#326 (MAINT) Bump ruby version
  .rubocop.yml
  puppet-strings.gemspec
Labels: maintenance

#328 (MAINT) Pin MDL to 0.11.0
  Gemfile
Labels: maintenance

#329 (CONT-228) Remove deprecated emit flags
  lib/puppet/face/strings.rb
  spec/acceptance/generate_json_spec.rb
Labels: backwards-incompatible

#333 (GH-332) Ensure PuppetStrings is loaded for tasks
  lib/puppet-strings/tasks.rb
Labels: bug

#334 (GH-332) Bump gem version to 3.0.1
  lib/puppet-strings/version.rb
Labels: bugfix
