Repository puppetlabs/puppet-strings, pull requests merged in 2024-01, with the labels that each got.

#380 pdksync - "(CAT-1618) - Add code coverage to ci"
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  Gemfile
  Rakefile
  spec/spec_helper.rb
Labels: maintenance

#381 pdksync - "(CAT-1618) - run code coverage on main"
  .github/workflows/ci.yml
Labels: maintenance

#379 Add new trusted contributor
  CODEOWNERS
Labels: maintenance

#378 Drop outdate Ruby version checks
  lib/puppet-strings/markdown.rb
  lib/puppet/face/strings.rb
Labels: maintenance, community

#373 (maint) Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: maintenance

#383 (CAT-1688) Upgrade rubocop to `~> 1.50.0`
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
Labels: bugfix

#384 pdksync - (CAT-1618) - Remove deprecated/obsolete codecov gem
  Gemfile
  spec/spec_helper.rb
Labels: maintenance
